= Lab 03 (Technical) Deploying an application with Docker

_This is an early stage lab. All that is required is that you do your best and present errors to the instructor and your classmates._

Reason for the change this quarter: The Vagrant-based pipeline previously used has become more and more unpredictable and error-prone. At this point, it is non-functional. Docker promises a more stable, flexible, and simpler way for you to assemble software stacks as building blocks of self-contained functionality.

The overall goals for this lab are for you to stand up Docker in your home directory *on the new server*, or else on your *own laptop.* (Do not do this on the old server, it does not have the capacity.)

You will run the official https://docs.docker.com/get-started/[Docker tutorial], through Part 5 (not 6). We'll take breaks and discuss how this is going for you all.

PLEASE make note of the following and DO NOT JUST TRY TO DO EVERYTHING IN THE TUTORIAL especially if you are doing this on the server.

== If you are doing this on the server


== If you are doing this lab on your laptop
