:linkattrs:

= Lab 03 (Technical) Deploying an application with Docker

_This is still an early stage lab. All that is required is that you do your best and present errors to the instructor and your classmates._

Learning objectives for this lab:

* Gain basic Docker skills using GCP
** Running pre-existing Docker containers
** Creating a Docker container with a simple application in it
* Moving your application to Docker

== Basic Docker skills

NOTE: It seems you can run the entire tutorial within the Google Cloud Shell, without the additional step of spinning up a VM. We are going to continue investigating this. 

* Study https://cloud.google.com/containers/.

* Log in via the web page (still working on getting ssh to work from command prompt immediately).

* Run https://cloud.google.com/cloud-build/docs/quickstart-docker[Quickstart for Docker^]

* Review https://cloud.google.com/compute/docs/containers/ 

* Run https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os

* With those preliminaires out of the way, noting any necessary adaptations, run the full Docker tutorial https://docker-curriculum.com/.

** We are using Google, not Amazon, so skip the Amazon-specific sections. 

== Replatforming your system

* On your Github account, set up an empty repo with the name "YOUREMAIL-dock-tut" (YOUREMAIL is your 8 char email account), and clone it down to your ~/repos directory on Google Cloud Shell. 

* Configure a basic static webserver along the lines of the last tutoria.

* Move your images and html file over to your new system. Run it. 

* Push your newly configured system back up to Github. 


== A basic main.tf file

* Using the below code as a basis, you can create a simple Terraform file (`main.tf`) to create a container-optimized VM. 

....
provider "google" {
  project = "INSERT YOUR PROJECT NAME HERE"
  region  = "us-central1"
  zone    = "us-central1-c"
}
resource "google_compute_instance" "dock-tut" {
  name         = "dock-tut"
  machine_type = "f1-micro"
  zone         = "us-central1-c"
  boot_disk {
    initialize_params {
      image = "cos-cloud/cos-stable"
    }
  }
  network_interface {
    network = "default"
    access_config {
      // Ephemeral IP
    }
  }
}
resource "google_compute_firewall" "default" {
 name    = "dock-net"
 network = "default"

 allow {
    protocol = "icmp"
  }

  allow {
    protocol = "tcp"
    ports    = ["22", "80", "8080", "1000-2000"]
  }
}

  output "ip" {
     value = "${google_compute_instance.dock-tut.network_interface.0.access_config.0.nat_ip}"
  }
....