= Tech lab 04 (version 3)

== Overall goal 

Track, with Github, Microsoft Azure and possibly ServiceNow, the course material on a technical level.

== Section II priorities: it's all about the team. 

. Recommended editor: VSCode

. Figure out public/private key for Github. 

. Form 3 teams.

. Each team member: Get a free student account for Azure. (Not sure if there is an approval cycle.) Do NOT give them a credit card. 

. Spin up a VM and access it there. 

. Get some software (any of the things we worked on last week) running on it in a way that others can view (preferably a simple curl that returns a string or a number).

. Put that software into version control, in the aitm-labs/svc* repo as appropriate. I control those repos? How do you do this using GitHub?

. Explore the Microsoft work management / Kanban capabilities. Connect them to Github pull requests. Update your software and ensure that the person making the changes does not push to master, but instead issues a pull request of a team mate (basic peer review).

. Connect Azure pipelines with GitHub so that you can automatically deploy on commit from Github. 




