= SEIS664 Lab 00

NOTE: We are in a bootstrapping phase. We need to get you set up on Github and Google Cloud so that you can learn Linux. But that means you need to execute some Linux without knowing much about it. Do your best to follow the instructions. 

== Setting up Slack

== Setting up Github account

Go to http://github.com and set up a user account (one per individual, even if you are in teams). You probably do NOT want to use your school email account name for this, as your Github account may be an asset throughout your career. *Choose a suitably professional user name.*

NOTE: You will have to keep track of TWO IDs and substitute them at appropriate times:
*YourStudentID* and *YourGithubID*.

Set up a private/public key pair for your Github credentials. Start by going to Git Bash under your Windows menu. 

Next, review these instructions: 

https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account

https://help.github.com/en/articles/testing-your-ssh-connection

and follow them. 

Autoconfigure your Git Bash to launch the ssh-agent every time: 

https://help.github.com/en/articles/working-with-ssh-key-passphrases

You can create a .profile file using Notepad+. 

Close and re-open Git Bash. 

Now, run this tutorial: 

https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

=== Clone this repository

A key strategy of this course is that the students contribute to the learning materials ongoing. Therefore, these instructions you are reading right now are something that we all collaborate on. You need to know how to change the instructions to help correct errors or add insights you may have developed as you work through them. 

When you have finished the tutorial, download this repo to your computer. Open Git Bash and type: 

`cd`

`mkdir repos`

`cd repos`

`git clone git@github.com:dm-academy/aitm-labs.git`

Now, you should have all the lab files locally on your machine. You can open them in Notepad++ or other text editor. In this way you can change them and submit changes back to the central repo as pull requests. Try submitting a minor change to this file via the techniques presented in the tutorial. Note that you will not be able to accept the change, as I am the maintainer of this file. I would have to approve. 

IMPORTANT: From this point forward, you are STRONGLY ENCOURAGED to submit issues and enhancements to the course documentation. Extra credit points are readily available for contributing to the class in this manner. Don't allow yourself to "get stuck." Communicate with your classmates in Slack and if you are still stuck then raise a Github issue. If you are stuck, the problem is in the instructions, and we need to fix it. 

== Accessing Google Compute Engine

For this lab we are going to work with Google Cloud to setup a micro-instance of a virtual machine.

As this is your first lab, please read this manual carefully and follow along. It may be difficult or nearly impossible to start over if you make certain key mistakes. 

You can create as many VMs as you want, but keep in mind that your account will be charged for each moment a VM is online. Note that you should never put your personal credit card information into Google Compute Engine. This is 100% free for you.

The reason we’re using a micro-instance is that it is free to your account, as long as you don’t send/receive too much data. More info here on that: http://cloud.google.com/free. We won’t be needing any amount of power behind the scenes, unless if you need it for your term project.

*Account Setup*

You should have received an email forwarded from myself containing information for signing up for Google Cloud. Your St. Thomas email is required for the first form, this is where you will get the coupon (Google requires a valid student account with a university or college).

The second email you get will be a coupon code to redeem. Click the link to redeem and then read the following very carefully.

YOU MUST HAVE A PERSONAL GMAIL ACCOUNT. IF YOU USE YOUR SCHOOL EMAIL THIS WILL NOT ONLY NOT WORK, BUT YOU WILL NOT BE ABLE TO FINISH THE LAB. 

When you go to sign up for coupons, make sure the icon for your personal Gmail account is active. You cannot complete this lab or this course using only your St. Thomas ID (which is managed through Microsoft Office 365).

Click the link in your email to sign up for the free Google Cloud credits, making sure to copy the unique code.

Note that my personal Gmail account (email redacted) is active. Also, the code above will not work for you, as I have redeemed it for teaching purposes. You should have a $50 credit in your account. If you run out of money, I can request more for you, however that will require turnaround time for Google to approve it.

Ok, now you should have a billing account. You can access this at http://cloud.google.com now whenever you want. Google Cloud itself is really outside the scope of this lab, however I’d recommend reading up on its capabilities (hint: there are a lot of cool things you can do with it).

You should be dumped to a screen that looks like this

This is the Billing page. It tells you how much money you have in your account. All of your Projects will be linked to this billing account. This is how cloud computing works.
We now need to create a project for the class. The project will contain all VMs related to the class. Click the Google Cloud Platform logo on the top left to bring you to the home page (also accessible via https://console.cloud.google.com).
You should see a card titled Project info. Click Go to project settings and you should see a similar window to this

Click New Project and name it <USTID>-SEIS664-2019-9, where <USTID> is your university ID (the first part of your email, before the "@", without the angle brackets). Select your newly created billing account and leave the organization alone. It should look like (2019, not 2018 though):

This may take a little while, depending on the speed of Google. At the top right you’ll see an icon like this:

If it is spinning, then Google is working in the background. You can click it for more information.
Once it’s done, select your newly-created project from the drop down at the top of your cloud console.

Now, you will create your VM.

*VM Creation*

First, click the options menu (3 horizontal lines) on the top left and then click Compute Engine.

VM instance creation will take a few minutes.
So now that's the instance is running (green check), open the instance by clicking its name and looking at the details and monitoring tabs.
Remote Access
It is now time to SSH into your server. Google Cloud makes this ridiculously easy to do in the browser. Go back to the VM instances page and click the SSH button:
This will pop open an SSH window, similar to this:
Yay! You are now in your Linux virtual machine. Now we should make sure our machine is up to date and install Apache. This is something that should be done fairly regularly to make sure things like security updates are applied to your software.
In the terminal, run (without the dollar sign, that is an indicator that you should type a command into the shell).
$ sudo apt-get update $ sudo apt-get upgrade $ sudo apt-get install apache2
Type y and hit enter to accept.
This is your microinstance. Take a screenshot of your browser window with the Apache default screen (should just be able to visit your external IP address). This is the one that you leave on all the time.
Windows VM
Go through the same process as before, but instead pick Windows Server 2016. Name it <lastname>-csi3670-windows-instance-1. Give it a n1-standard-1 (1 vCPU, 3.75 GB memory) CPU and RAM. Anywhere from 30-50GB should be fine for HDD space.
Create it, turn it on. This one you should turn off when you are done!.
Click the RDP icon in Google Cloud to launch a Remote Desktop session (either use the downloaded
.rdp file or install the Chrome extension). If you're on Mac or Linux, look up how to connect via Remote Desktop.
Open up Windows Server. Install the Web Server Role. Add the FTP feature. When you are done, take a screenshot of your Server Manager to demonstrate that you installed the role appropriately.
Turn off the Windows VM when you are done!
Fill out the report on the last page and turn in ONLY the report page!
85 points
Name:
Date:
Homework 1:
1. Paste the two screenshots from above here. (40 points)
2. Go to https://cloud.google.com/products/ and pick 2 random Google products that are available in their cloud platform (meaning, you have access if you wish). Briefly describe (1) what it is and (2) why it might be helpful. Do not simply just copy and paste the descriptions. (10 points).
3. Assume you are installing Windows Server 2012. Provide two reasons for selecting one ver-sion over another. For example, why would you want to install the Foundation edition over the Datacenter edition? Why would you want Standard over Essentials? (10 points)
4. Look over some of the available roles that Windows Server provides. Select two and describe their purpose. (10 points).
5. What is the difference between Type-0 (full) and Type-1 (para) virtualization? (10 points)
6. What is the IP address of your Ubuntu virtual machine? (5 points)