= Lab 00  Course setup

CONTINUOUS IMPROVEMENT FEEDBACK FOR Spring 2015:

* Test this well
* Provide an overview of the objectives
* Explain the basic Unix commands when first used


_Retrospective notes after 2015 fall run: this needs complete QA & cleanup before Spring 2016. Strongly recommend not linking to other resources. Need to do our own Putty install & config. Not using vi. _

_There should be some discussion of the difference between password and ssh login and why ssh is preferable._


In this lab, you will set up the tools and access you need for the rest of the semester.

== Objectives for this lab:
* Locate and use the Blackboard and Slack collaboration tools
* Configure your terminal emulator
* Securely connect to course server via ssh and (possibly) x-windows
* Collaborate and support each other.

This lab suffers from what is called a https://en.wikipedia.org/wiki/Catch-22_(logic)[Catch-22], a "no win" situation. You can't learn Linux without connecting to the server, and you can't connect to the server without learning a little Linux.

Because of this, you will go through a set of instructions that may not make much sense. You will have plenty of support from your instructor and hopefully your classmates. Do NOT get discouraged. The first thing you will do next week is run a Linux tutorial. We've had good experiences in this class getting everyone up to speed on these basics.

== Prerequisites
You need access to a Windows (7 or greater), Mac OS X (10.9.5 or greater) or Ubuntu Linux machine on the St. Thomas network. It can be your machine or one of the machines in the classroom.

If you have your own machine, you should be comfortable installing software on it.

If you want to use a tablet (iPad or Android), you are ON YOUR OWN. (It probably could be done - SSH & X clients exist - but we don't have the bandwidth to support it.)

Same for any other platform.

== Tasks

=== Using Blackboard
You should be familiar with Blackboard from previous courses. If you are not, please let the instructor know.

We will use Blackboard for the syllabus,

=== Collaborating on Slack

* Slack will be the main communication channel.
* Navigate to https://seis660.slack.com/[https://seis660.slack.com/].
** Click "create an account" and remember your password.
** Confirm you can read messages. Try posting to the https://seis660.slack.com/messages/general/[#general] thread.
** The channels are not cleared from the previous semester. Have a look, you'll get a feel for the class. SEIS660 alumni may lurk and assist if they feel like it, as long as they are constructive.

=== Setting up your terminal emulator

* Classroom machine: PuTTY and PuTTYGen should be installed
* Windows on your laptop: http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html[install PuTTY and PuTTYGen] and make sure you can find the shortcuts.
** Download the latest installer (*putty-0.66-installer.exe* as of Feb 2016) and run it. (Save, then run. You may need to approve some security warnings. Accept all the defaults. No need to open the README.)
* On your MacOS laptop, go to Applications|Utilities|Terminal and put it in your Dock.

You may also use Cygwin, TeraTerm, Bitvise, or any other SSH client of your choice. You’re on your own for this.

You will be provided usernames, temporary passwords, and the server name in class. Use your terminal emulator to log into the server, by entering the server address, your name, and password as appropriate to PuTTy, or by simply going:

 > ssh <yourStThomasID>@<servername>

on the Mac OS.

Once you have logged in, do not type anything or "move around" in the directory structure. You should be in your home directory in a "clean," newly initialized account. Try:

 $ mkdir .ssh
 $ cd .ssh
 $ touch authorized_keys

and then, only for Mac users:

 $ exit

(Windows users will need to stay logged in for the next part.)

IMPORTANT: The "$" and ">" above represent the prompt the operating system displays for you. It may have your name or other stuff before it. In rare cases, it might be a different character like "#" or even "&". In any case, you don't type the prompt character.

If there are any errors post them to the discussion room for assistance.

NOTE: You will not be able to login via password after this session. The "cleartext login" functionality in sshd_config will be https://help.ubuntu.com/community/SSH/OpenSSH/Configuring[disabled].

=== Configuring SSH - Windows

*Windows machines (both classroom machines and your laptop):* follow these instructions

http://www.ualberta.ca/CNS/RESEARCH/LinuxClusters/pka-putty.html

If you have questions, check the chat room.

=== Configuring SSH - Mac OS

IMPORTANT: On the Macintosh, be sure you are logged out of the course server. These next commands need to be performed on your local machine, while connected to the network.

If you're not already in it, bring up your Terminal application (under Applications|Utilities). *At the window for your local computer*  type:

 $ cd ~/.ssh
 $ ssh-keygen

It will suggest a name, id_rsa; that is fine.

You can enter a blank passphrase.

 $ cat id_rsa.pub

You will get output like:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRycwk4jklWQyzmXi/QtM6ky+85O3C5291GDCOuvzn3Q4t83Sv2wkN69aLhLk53Lfw5SU1unOWb0Cj2xi+El8D5oR+Yncovz53uqSFmiDuHKNH3bQBUS4v15n6AkJ9nqvJtJZ0iuFD1zSlP3JqeSk5e2NPCmqSbWKEOijOsGWeVHxbs2z8I5PcD2Yrd9nDwhpg84eRUHamgZvvDS83lb5A0cUK5lQXr6zinAhWsELtCZCfSOYf5gaL3ADI53hSHekDMeJvK0r+em0NLb9dwSJnJJYBJ+Eb8xhj+hSrw3pkSHGhsPYDth99vkDnPdSQNrNoVhwmJxa3T4sbLy2O+WWn xxxxxx@xxx..xxx.local
```
Copy the output to your Clipboard (highlight and Command-C). Log back into the course server with your name and password.

 $ ssh <yourStThomasID>@<servername>
 [login]

 > cd ~/.ssh
 > vi authorized_keys

. Press the i key to go into insert mode. (It should say INSERT at the bottom.)

. Paste your key with a right click of your mouse.

. Hit the "ESC" or "Escape" key, which should be at the top left of your keyboard. "INSERT" should disappear.

. Type ":wq!"   (NO QUOTES)

. Now, type 'exit'.

You should now be able to log into the server by going

 ssh yourname@servername.domain

and it will NOT require a password, because you are using your key pair to authenticate.

====
*QUESTION:*

Why didn't I automate this? It would have been a simple script to set it all up in advance and provide you all your private keys. Discuss.
====

=== Configuring X windows

We will spend some time as a class determining whether and how X-windows is working for you all.

NOTE: As of Fall 2015, there is new X-windows software in the lab. We will all be getting familiar with it.

To use X-windows, log into seis660, enabling X windows for the connection, as described in the following.

*Windows* If you are on a windows machine using Putty you will have a checkbox (that may have defaulted to checked) to enable X. If someone figures out the compression options, please suggest.

Open the X windows client, http://sourceforge.net/projects/xming/[XMing] (install if necessary).

If you are using your own PC, you can also install http://wiki.x2go.org/doku.php/doc:installation:x2goclient[X2Go] or MobaXTerm.

*Mac OS* As of February 2015, Macs no longer are bundled with X. In newer machines, the http://xquartz.macosforge.org/landing/[XQuartz application] X windows client needs to be downloaded and installed on your computer.

Log in to the classroom server with the following options if you are on a Mac:

    ssh -XC yourID@server.domain


*All OS* The quickest test for X-windows is to run the command

    xclock

If it does not work, it may be an issue with X-windows on the client.

If you have trouble, do not raise your hand immediately. Instead, first ask the question in the chat room.

WHEN you are done with the lab, log into the chat room and discussion board and assist until all of your classmates are done.

== Common errors

* Instructor creating .ssh directory or authorized_keys as root, with incorrect permissions
* Student failing to load private key into PuTTY every time (either manually or through incorrect use of profiles)
