= Lab 02 (Technical) IT Infrastructure

== The Google Cloud Shell
The Google Cloud Shell is a specialized VM. 

== Terraform

* 

* Run the Terraform GCP tutorial https://www.terraform.io/docs/providers/google/getting_started.html and safe your file(s) in the repo. 
** You will need to create a GCP credential. I suggest storing it in `~/cloud/`.
** You will need to create or edit your `.bash_profile` to create the GOOGLE_CLOUD_KEYFILE_JSON environment variable. 

IMPORTANT: Going forward, you should ONLY provision and deprovision GCP resources with Terraform. 

== Accessing your VMs 

There are various ways to 

It's going to be a lot easier if every VM is immediately set up to be accessed with Mac Terminal or Git Bash on Windows. There are a couple ways to do this, but for maximum flexibility I recommend installing the the Cloud SDK, https://cloud.google.com/sdk/docs/quickstarts. 


== Local Terraform (optional)

* The Google Cloud console is flexible and works on the classroom workstations as well as any device of yours. But many run Terraform locally for the greatest flexibility. 

* You can run Terraform on your laptop. https://learn.hashicorp.com/terraform/getting-started/install.html. Terraform does not have an installer. You simply place the file in a directory that is on your $PATH. What is $PATH? It is an environment variable that lists all the directories where applications might be found. I recommend /usr/local/bin on the Mac and C:\Users\<your ID\bin on the PC (assuming you're be using Git Bash; if you are using PowerShell then you'll probably want it in C:\Program Files) You will need administrative privileges to modify either

* Create a new Github project titled Lab02-<your St. Thomas ID>. That is, if your St. Thomas email is ande0001@stthomas.edu, name it Lab02-ande0001. 

* Clone the new repo down to your workstation. (Request assistance if you need it with Github.))