= Lab 08: Project Management

Assume your startup has been acquired by a larger company, and through a series of re-organizations they've made you an "offer you can't refuse" to help implement an ERP system. The project is a new kind of work for you; it is waterfall, not Agile, primarily because you don't need to develop new software, but rather configure a vendor supplied package. At least, that is the theory.


IMPORTANT: This is a highly experimental, first generation lab. It's not clear how much it is reasonable to expect in an 3 hour lab intended to introduce project management. I don't know how detailed/prescriptive to be, either.

I look forward to having class discussion on how the lab can be improved.

== Learning objectives

The purpose of this lab is to teach you the fundamentals of project management through use of an online tool.

In this lab, we will attempt to demonstrate:

* the creation of a detailed project plan, including timelines, resources, and costs
* the tracking of execution against that plan
* the various forms of uncertainty that can arise and how to handle them
* the intersection of product management and project management, and the influence of Agile

== The premise

The lab is based on a "project" of four "sub-projects" that will have some interdependencies.

The basic objective of the program is to implement a large scale Enterprise Resource Planning system for a manufacturing supply chain. (It is modeled on the typical activities and methods of systems integrators such as Accenture or IBM Global Services.)

The four sub-projects are:

* Vision, charter, and requirements
* Core technical platform
* Business configuration
* Global deployment

The project is scheduled to start 1/1/2016, and must be finished by 12/31/2016 without fail.

It has a $35 million budget.

The tentative plan is as follows:

|===
|Period | Task
|Jan-Feb |Vision, charter, and requirements
|March-June|Core technical platform
|March-Sep|Business configuration
|May-Dec|Global deployment
|===

Notice that there is overlap between the "Core technical platform" and the "Business configuration" activities. It is assumed that research and requirements gathering can be accomplished before the platform is physically acquired and installed.

Notice that this project involves relatively little "development" per se, as the ERP system is more of a configurable framework. However, there will be some needs to customize screens and build reports.

In general, this is a classic "waterfall" project that can (mostly) be understood in advance.

== Team approach

You all will remain in your teams of 5-6 people. Each SEIS660 team will be responsible for developing one version of the project plan.

*Within each class team*, the roles will be structured in the following way:

* *PMO Lead* represents the the Project Management Office, responsible for the overall program vision,  integration of the sub-team plans, and reporting status to leadership.
* *Technical Lead* represents the Technical Architecture team, responsible for the core system: hardware, software, configuration, and deployment
* *Process Lead* represents the Process team, responsible for understanding business requirements
* The *Change Lead* represents the Organizational Change Management team, responsible for rollout, training, organizational communication.

There are only four roles, so you will be able to have one or two people float in response to demand.

== Setup
All of you now have access to the Clarizen online (SaaS) project management tool. Each team has had its own project created.

== Project details
NOTE: This is the part of the lab that requires much further development. I do not want to start off too detailed, however.

First, as a team read

* https://en.wikipedia.org/wiki/Enterprise_resource_planning[Wikipedia on ERP]
* http://txprojectone.org/documents/ERP_Advisory_Council_Report.pdf[State of Texas ERP plan]

Note that for a variety of reasons, your company has opted to host the ERP system internally. This means that your technical team needs to handle asset acquisition, data center capacity, network capacity, SAN sizing, and so forth. The ERP vendor will be able to provide guidance on much of this, based on the anticipated workload.

The sections below are intended as a start, but not comprehensive. You can and should do some online research (e.g. Google "Sample ERP implementation plan") for further details. 

=== Vision, charter, and requirements
You do not need to write a vision, charter, and requirements spec. You need to document the plan to deliver them. How long do you think you will need for each of these?

=== Core technical platform
The core technical platform plan at a minimum should include the following tasks:

* Hardware general design
** Select ERP product
** Select supporting software (database, middleware, batch scheduler, OS, hypervisor if used)
** Size and select hardware
** Size SAN
** Get hardware acquisition approval (milestone)

* Software & platform detailed design
** ERP core installation
** Database detailed design
** SAN detailed design

* Hardware implementation
** Order hardware
** Receive hardware
** Install hardware
** Configure hardware

=== Business configuration
* Determine business requirements
* Identify key master data sets
* Identify necessary data cleanup/reconciliation work
* Identify regionalization issues
* Identify necessary process variations due to local conditions
* Convert master data sets

* Determine reporting requirements
* Build and test reports

=== Global deployment
==== Technical deployment (starts in May)

* Operations architecture
** Production scheduling
** Define backup strategy
** Define support teams and escalations

==== End user rollout (starts in Oct)

* Develop training materials
* Train the trainers
* Train the users
* System cutover 12/1/2015

== Approach

The objective is not to get a perfect project plan. For a system of this scale, that would require days or weeks of effort by experienced professionals.

At least at first, breadth is better than depth. That is, it is better to have a high level plan for all of the project, than a detailed plan for one section with the rest left completely undone.

You should develop your project with a top-down approach, and make liberal use of "TBD" placeholders. It is perfectly acceptable to have tasks such as "Further develop project plan to detailed task level"  HOWEVER, that placeholder task SHOULD have a "done by" date you are managing to! You need the details by the time the work commences.

You should be tracking the dependencies between the various tasks. I am not telling you what they are; you should carefully discuss them on your team - this is a key part of the learning for this lab.

Finally, you need to identify the skills and resources you will need. Consider the above requirements, and consult the Skills Framework for the Information Age:

http://www.sfia-online.org/en/sfia-6/skills/skills-home

You will need to set up a personal, free account. Do so now.

Don't go crazy, but identify about 10-15 skills you need and enter them in your project plan.

Now, because all 4 teams are using the same list of skills and people, each team should preface its data with its team number - e.g. "01-Database Administration" would indicate that Team 01 sees Database Administration as a primary skill.

To add workers/resources to the project, you need to use a dummy email address and check the box to NOT email. I recommend email addresses and names of the form:

xx-tim@seis660.com, xx-tim

where xx is your team #.

You can add skills to individuals by "add related" on either the skill or individual page.

You should add hourly rates to individuals. When you combine an individual with an hourly rate with a given task duration, you can start to develop a project budget. Go to Reports|Cost & Revenue Forecast All Projects.

Populate your project with a sufficient number of tasks and people to consume 80% of the budget. Keep the other 20% in reserve. I will be monitoring and intervening as we go, and the project will progress throughout the hour.

== other tools considered
http://www.aha.io/
