

 2016 Apr note: Need to have printed sheet or poster with both backlog and business rules

  Rules on printed cards for all to reference?? - not good enough with me just verbally providing directions.

 Ran short of backlog - they got quite quick - or make each building more difficult (higher quality required?) - unclear definition of done there

  Not enough work for vehicle team

  Not sure how well the functional silo is getting across

  Definition of done: DEPLOYED (missed this until middle of iteration 2)

  2 iterations on first was good

  Big bottleneck with infrastructure team being perfectionist & preventing deployments

  Need concept of "minimum viable town"

  PMS walked away from kanbans & didn't maintain

  No meaningful estimation

  8 minute sprints are probably OK




=== NOTES

Batches of 10 dice go on large plates. 1-3 dice batches on small plates

configuration 1: functional teams w/manager - manager dispatches work in large batches (10)
configuration 2: functional teams, product owner can interact directly, work still in large batches
configuration 3: product teams, small batches (3+3+2+2), flow across specialists in order
configuration 4: product teams, self-organizing, anyone can transform dice BUT higher probability of rework.

rework probabilities: 10% per die (1/10)
1-(9/10)^n, n=batch size



how to think about feedback

BA sets all dice to 1 & forwards
Dice are laid out on a card with 10 spaces.

Dev sets all dice to 2 & forwards. But they discover... what?


  there are n major products
  each product consists of a set of releases
  each release is a 12"x12" card with a specific configuration
  of complex requirements

  * dice (with a particular side up)
  * cards
  * small, specified Lego structures

they can choose what they want to build - they assemble the cards from primitives

a primitive has a

 - point value
 - an artifact (dice, cards, Lego)
 - a set of states for the artifact (discovery, delivery, deployment, ops)



  dimensions:

  * lifecycle stages
  * supply specialists
  * products




  each set of
