

 2016 Apr note: Need to have printed sheet or poster with both backlog and business rules

  Rules on printed cards for all to reference?? - not good enough with me just verbally providing directions.

 Ran short of backlog - they got quite quick - or make each building more difficult (higher quality required?)

  Not enough work for vehicle team

  Not sure how well the functional silo is getting across

  Definition of done: DEPLOYED (missed this until middle of iteration 2)

  2 iterations on first was good

  Big bottleneck with infrastructure team being perfectionist & preventing deployments

  Need concept of "minimum viable town"

  PMS walked away from kanbans & didn't maintain

  No meaningful estimation

  8 minute sprints are probably OK


== ideas for dice game

objectives:

* illustrate matrix management
* illustrate queuing versus collaborative teams
* illustrate feedback & information creation issues

how to think about feedback

BA sets all dice to 1 & forwards
Dice are laid out on a card with 10 spaces.

Dev sets all dice to 2 & forwards. But they discover... what? 


  there are 6 major products
  each product consists of a set of releases
  each release is a 12"x12" card with a specific configuration
  of complex requirements

  * dice (with a particular side up)
  * cards
  * small, specified Lego structures

they can choose what they want to build - they assemble the cards from primitives

a primitive has a

 - point value
 - an artifact (dice, cards, Lego)
 - a set of states for the artifact (discovery, delivery, deployment, ops)




  dimensions:

  * lifecycle stages
  * supply specialists
  * products




  each set of
